# Generated by Django 5.1.1 on 2024-10-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('заработная плата', 'Заработная плата'), ('пенсия', 'Пенсия'), ('стипендия', 'Стипендия'), ('выигрыш', 'Выигрыш'), ('доходы от индивидуальной предпринимательской деятельности', 'Доходы от индивидуальной предпринимательской деятельности'), ('доходы от недвижимости', 'Доходы от недвижимости'), ('доходы от депозита', 'Доходы от депозита'), ('подарки', 'Подарки'), ('наличные денежные средства', 'Наличные денежные средства'), ('прочие доходы', 'Прочие доходы')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
