# Generated by Django 5.1.1 on 2024-10-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0011_remove_category_user_alter_category_name'),
        ('homebuhweb', 'add_category'),
    ]

    operations = [
    ]
