# Generated by Django 5.1.1 on 2024-10-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0016_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carexpense',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='monthly_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
