# Generated by Django 5.1.1 on 2024-10-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0023_carexpense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carexpense',
            name='subsubcategory',
        ),
    ]
