# Generated by Django 5.1.1 on 2024-10-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0024_remove_carexpense_subsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carexpense',
            name='subsubcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_expenses', to='homebuhweb.expense'),
            preserve_default=False,
        ),
    ]
