# Generated by Django 5.1.1 on 2024-10-20 10:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0019_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedexpense',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='months_to_save',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
