# Generated by Django 5.1.1 on 2024-10-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0021_alter_myuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
