# Generated by Django 5.1.1 on 2024-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0026_myuser_remove_carexpense_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='credit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
