# Generated by Django 5.1.1 on 2024-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0027_delete_myuser_credit_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit_term',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
