# Generated by Django 5.1.1 on 2024-11-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0028_alter_credit_credit_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_term',
            field=models.IntegerField(),
        ),
    ]
