# Generated by Django 5.1.1 on 2024-11-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebuhweb', '0030_credit_is_paid_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='is_paid_off',
        ),
    ]
